version: 2.1
description: Tools for testing Python projects.

commands:

  run-with-coverage:
    parameters:
      command:
        type: string
    steps:
      - run:
          name: "Run Tests"
          command: |
            python --version
            mkdir -p coverage_output
            export COVERAGE_FILE=coverage_output/.coverage.$CIRCLE_BUILD_NUM
            << parameters.command >>
      - persist_to_workspace:
          root: coverage_output
          paths:
            - .coverage.*

  pip-run-tests:
    parameters:
      prepare:
        type: steps
        default: []
      command:
        type: string
        default: pytest --cov
      install:
        type: string
        default: "-e .[test]"
      extra_packages:
        type: string
        default: ""
      sudo:
        default: true
        type: boolean
    steps:
      - checkout
      - run:
          name: "Install Project"
          command: "<<# parameters.sudo >>sudo <</ parameters.sudo >>pip install << parameters.extra_packages >> << parameters.install >>"

  poetry-run-tests:
    parameters:
      prepare:
        type: steps
        default: []
      command:
        type: string
        default: poetry run pytest --cov
    steps:
      - checkout
      - run:
          name: "Install Project"
          command: poetry install
      - steps: << parameters.prepare >>
      - run-with-coverage:
          command: << parameters.command >>

jobs:

  pip-run-tests:
    parameters:
      image:
        type: string
      prepare:
        type: steps
        default: []
      command:
        type: string
        default: pytest --cov
      install:
        type: string
        default: "-e .[test]"
      extra_packages:
        type: string
        default: ""
      sudo:
        default: true
        type: boolean
    docker:
      - image: << parameters.image >>
    steps:
      - pip-run-tests:
          prepare: << parameters.prepare >>
          command: << parameters.command >>
          install: << parameters.install >>
          extra_packages: << parameters.extra_packages >>
          sudo: << parameters.sudo >>

  poetry-run-tests:
    parameters:
      image:
        type: string
      command:
        type: string
        default: poetry run pytest --cov
      prepare:
        type: steps
        default: []
    docker:
      - image: << parameters.image >>
    steps:
      - poetry-run-tests:
          prepare: << parameters.prepare >>
          command: << parameters.command >>

  coverage:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: coverage_output
      - run:
          name: "Check coverage"
          command: |
            sudo pip install coverage
            coverage combine coverage_output/
            coverage report --show-missing --fail-under=100

  release:
    parameters:
      config:
        type: string
        default: pyproject.toml
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: "Release"
          command: |
            sudo pip install carthorse
            carthorse --config << parameters.config >>
