version: 2.1
description: Tools for testing Python projects.

commands:
  run-with-coverage:
    parameters:
      command:
        type: string
    steps:
      - run:
          name: "Run Tests"
          command: |
            python --version
            mkdir -p coverage_output
            export COVERAGE_FILE=coverage_output/.coverage.$CIRCLE_BUILD_NUM
            << parameters.command >>
      - persist_to_workspace:
          root: coverage_output
          paths:
            - .coverage.*


jobs:
  poetry-run-tests:
    parameters:
      image:
        type: string
      command:
        type: string
        default: poetry run pytest --cov
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run:
          name: "Install Project"
          command: poetry install
      - run-with-coverage:
          command: << parameters.command >>

  coverage:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: coverage_output
      - run:
          name: "Check coverage"
          command: |
            sudo pip install coverage
            coverage combine coverage_output/
            coverage report --show-missing --skip-covered --fail-under=100

  release:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: "Release"
          command: |
            pip install carthorse
            carthorse
